data:
  market_file: "data/market_research.csv"
  farmer_file: "data/farmer_advise_dataset.csv"
  
  market_target: "Market_Price_per_ton"
  farmer_yield_target: "Crop_Yield_ton"
  farmer_sustainability_target: "Sustainability_Score"
  
  market_features:
    - Market_Price_per_ton
    - Demand_Index
    - Supply_Index
    - Competitor_Price_per_ton
    - Economic_Indicator
    - Weather_Impact_Score
    - Seasonal_Factor
    - Consumer_Trend_Index
    
  farmer_features:
    - Soil_pH
    - Soil_Moisture
    - Temperature_C
    - Rainfall_mm
    - Crop_Type
    - Fertilizer_Usage_kg
    - Pesticide_Usage_kg
    - Crop_Yield_ton
    - Sustainability_Score